### ISSUE TITLE
Segmentation fault on Ubuntu 16.10

### ISSUE THREAD

**Issue by jackBzzz** [spencerparkin/RubiksCube#1]
Hi,

I upgraded yesterday to 16.10 from 16.04 and tried to run the snap "rubecube". However, it simply throws a "Segmentation fault" and exits.

**Comment by spencerparkin** [comment]
Thanks for letting me know.  I think I'm on 16.04.  I will try upgrading if I can to see if I can reproduce the crash.  I don't have an ETA as it is extracurricular work.  If you have time to dig into the code, it would be much appreciated.  In the mean time, I'll see what I can do.

**Comment by jackBzzz** [comment]
Oh, I think you should stay with the stable version.. I solved the issue by removing snapd
`apt purge snapd`
reinstalling it
`apt install snapd`
and then reinstalling rubecube
`snap install rubecube`.

Now it works!
